version: '3'
services:
  app:
    build:
      context: .
    container_name: 'api-docker-container'
    volumes:
      - ./src:/server/src
    tty: true
    ports:
      - "3333:3333"
    networks:
      - node-networks

networks: 
  node-networks:
    driver: bridge
  